(defun path-to-one (number)
  (if (<= number 1)
      (format t "1")
      (let ((direction 0)
	    (remainder (mod number 3)))
	(cond ((= 2 remainder) (setf direction 1))
	      ((= 1 remainder) (setf direction -1))
	      (t (setf direction 0)))
	(format t "~A ~A~%" number direction)
	(path-to-one (/ (+ number direction) 3)))))
