#!/bin/sh

SILENTMODE="/Users/${USER}/Desktop/music=no"
LOGPATH="/Users/${USER}/song.log"
TMPLOG="/tmp/song.log"
key="$1"
FILE="/Users/${USER}/class_songs/${1}.mp3"
TIME=""
SAY="/usr/bin/say"

/usr/bin/tail -n 10 ${LOGPATH} > ${TMPLOG}
/bin/mv ${TMPLOG} ${LOGPATH}

# TURN OFF SLEEPING FOR 3 HOURS
# -s is no sleep, default is -i (do not idle sleep)
/usr/bin/caffeinate -u -t 10800 &

# Get an early abort if the song shouldn't play
if [ -e ${SILENTMODE} ]
then
	/bin/echo -n "NOT PLAYING ${key} :: ${SILENTMODE} exists @ " >> ${LOGPATH}
	/bin/date >> ${LOGPATH}
	exit
fi

/usr/bin/osascript -e 'set volume 4'

case ${key} in
    say)
	FILE=${SAY}
	/usr/bin/osascript -e 'set volume 8'
	;;
    lunch)
	/usr/bin/osascript -e 'set volume 8'
	;;
    math)
	TIME="-t 40"
	;;
    socialstudies)
	TIME="-t 32"
	;;
    welcome)
	/usr/bin/osascript -e 'set volume 8'
	TIME="-t 11"
	;;
    howfar)
	/usr/bin/osascript -e 'set volume 8'
	;;
    *)
	;;
esac

if [ -e ${FILE} ]
then
    if [ "say" = ${key} ]
    then
	# LOG THE ACTION
	/bin/echo -n "${SAY} ${2}: " >> ${LOGPATH}
	/bin/date >> ${LOGPATH}
	${SAY} "${2}"
    else
	# LOG THE ACTION
	/bin/echo -n "Run ${key} song: " >> ${LOGPATH}
	/bin/date >> ${LOGPATH}
	# PLAY THE SONG
	/usr/bin/afplay ${TIME} ${FILE}
    fi
else
    # LOG THE FAILURE
    /bin/echo -n "Run ${key} song: FAILED {DOES NOT EXIST} " >> ${LOGPATH}
    /bin/date >> ${LOGPATH}
fi
