#!/bin/sh
/usr/bin/osascript -e 'set volume 4'

LOGPATH="/Users/brunellek/song.log"
TMPLOG="/tmp/song.log"
key="$1"
FILE="/Users/brunellek/classsongs/${1}.mp3"
TIME=""

/usr/bin/tail -n 10 ${LOGPATH} > ${TMPLOG}
/bin/mv ${TMPLOG} ${LOGPATH}

case $key in
	lunch)
		/usr/bin/osascript -e 'set volume 8'
	;;
	math)
		TIME="-t 40"
	;;
	socialstudies)
		TIME="-t 32"
	;;
	*)
	;;
esac

if [ -e ${FILE} ]
then
	# LOG THE ACTION
	/bin/echo -n "Run ${key} song: " >> ${LOGPATH}
	/bin/date >> ${LOGPATH}
	# PLAY THE SONG
	/usr/bin/afplay ${TIME} ${FILE}
else
	# LOG THE FAILURE
	/bin/echo -n "Run ${key} song: FAILED {DOES NOT EXIST} " >> ${LOGPATH}
	/bin/date >> ${LOGPATH}
fi

# TURN OFF SLEEPING FOR 3 HOURS
# -s is no sleep, default is -i (do not idle sleep)
/usr/bin/caffeinate -u -t 10800 &
